apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-demo
data:
  virtual_host: "vhost1.localhost.com"
  index.html: |
    <html>
      <h1>Yasmim linda!!!</h1>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxc
  name: nginxc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxc
  template:
    metadata:
      labels:
        app: nginxc
    spec:
      containers:
      - image: nginx
        name: nginxc
        env:  
          - name: VIRTUAL_HOST
            valueFrom:
              configMapKeyRef:
                name: nginx-demo
                key: virtual_host
        volumeMounts:
        - name: index-html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html       
      volumes:
        - name: index-html
          configMap:
            name: nginx-demo
            items:
            - key: "index.html"
              path: "index.html"          