apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-demo
data:
  virtual_host: "vhost1.localhost.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxc
  name: nginxc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxc
  template:
    metadata:
      labels:
        app: nginxc
    spec:
      containers:
      - image: nginx
        name: nginxc
        env:  
          - name: VIRTUAL_HOST
            valueFrom:
              configMapKeyRef:
                name: nginx-demo
                key: virtual_host